### PR TITLE
Battery Soc & Battery Temp + HACS Compatibility

### PR DESCRIPTION
**Pull request by BigManDave**
Good Afternoon,
I've added sensors for Battery SoC and Battery Temperature. SoC even has a dynamic changing icon! :)
I've also fiddled with the structure of the repo a bit so that the integration can be manually added using HACS.

Hope you like it!

### CODE REVIEW

**Comment by macxq** [comment]
Awesome work @BigManDave Thank you 🙇

**Comment by macxq** [comment]
There are some conflict you need to resolve to be able to merge it

**Comment by BigManDave** [comment]
@macxq Hm, I've just tried copying your changes to manifest.json but it's still saying there's conflicts.
image

**Comment by macxq** [comment]
Editing the files will not work , you need to use command `git merge name_of_the_branch` please add me to you project as a contributor  i will be able to help if this will not work

**Pull request merged**
